#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️ Checking your project before committing...'

# Check Prettier standards
npm run format:check ||
(
    echo '🤢 Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)
